In [1]:
"""Pagerank algorithm with explicit number of iterations.

Returns
-------
ranking of nodes (pages) in the adjacency matrix

"""

import numpy as np

def pagerank(M, num_iterations=100, d=0.85):
    """pagerank: The trillion dollar algorithm.

    Parameters
    ----------
    M : numpy array
        adjacency matrix where M_i,j represents the link from 'j' to 'i', such that for all 'j'
        sum(i, M_i,j) = 1
    num_iterations : int, optional
        number of iterations, by default 100
    d : float, optional
        damping factor, by default 0.85

    Returns
    -------
    numpy array
        a vector of ranks such that v_i is the i-th rank from [0, 1],
        v sums to 1

    """
    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    for i in range(num_iterations):
        v = d * M @ v + (1 - d) / N
    return v


M = np.array([[0, 0, 0, 0, 1],
              [0.5, 0, 0, 0, 0],
              [0.5, 0, 0, 0, 0],
              [0, 1, 0.5, 0, 0],
              [0, 0, 0.5, 1, 0]])
v = pagerank(M, 100, 0.85)

v

array([[0.25419178],
       [0.13803151],
       [0.13803151],
       [0.20599017],
       [0.26375504]])

In [22]:
import numpy as np

def pagerank(M, num_iterations=100, d=0.85):
    N = M.shape[1]
    print(N)
    
    v = np.random.rand(N, 1)
    print(v)
    print()
    
    v = v / np.linalg.norm(v, 1)
    print(v)
    print()
    
    print("START ITERATION")
    print()
    for i in range(num_iterations):
        v = d * M @ v + (1 - d) / N
        print(v)
        print()
        
    return v


M = np.array([[0, 0, 0, 0, 1],
              [0.5, 0, 0, 0, 0],
              [0.5, 0, 0, 0, 0],
              [0, 1, 0.5, 0, 0],
              [0, 0, 0.5, 1, 0]])
v = pagerank(M, 5, 1)

v

5
[[0.72950127]
 [0.17419045]
 [0.57023936]
 [0.09764454]
 [0.54383159]]

[[0.34485146]
 [0.0823437 ]
 [0.26956482]
 [0.04615874]
 [0.25708128]]

START ITERATION

[[0.25708128]
 [0.17242573]
 [0.17242573]
 [0.2171261 ]
 [0.18094115]]

[[0.18094115]
 [0.12854064]
 [0.12854064]
 [0.2586386 ]
 [0.30333897]]

[[0.30333897]
 [0.09047058]
 [0.09047058]
 [0.19281096]
 [0.32290892]]

[[0.32290892]
 [0.15166949]
 [0.15166949]
 [0.13570586]
 [0.23804625]]

[[0.23804625]
 [0.16145446]
 [0.16145446]
 [0.22750423]
 [0.21154061]]



array([[0.23804625],
       [0.16145446],
       [0.16145446],
       [0.22750423],
       [0.21154061]])